In [28]:
import pandas as pd
import warnings

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
warnings.filterwarnings("ignore")

In [5]:
data = pd.read_csv("glass.csv")

In [6]:
data.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [7]:
data.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64
dtypes: float64(9), int64(1)
memory usage: 16.8 KB

In [10]:
data.head(1)

        RI     Na    Mg   Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.1  71.78  0.06  8.75  0.0  0.0     1

In [13]:
x= data.drop(labels="Type",axis = 1)
y = data[["Type"]]

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=12,stratify=y)

In [20]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
y_train_pred = model.predict(x_train)
print("Accurcy Score"  , accuracy_score(y_train,y_train_pred))

Accurcy Score 0.775

In [21]:
for i in range (1,41):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    y_train_pred = model.predict(x_train)
    print(" For ",i," Negn Accurcy Score"  , accuracy_score(y_train,y_train_pred))

 For  1  Negn Accurcy Score 1.0
 For  2  Negn Accurcy Score 0.8375
 For  3  Negn Accurcy Score 0.7875
 For  4  Negn Accurcy Score 0.775
 For  5  Negn Accurcy Score 0.775
 For  6  Negn Accurcy Score 0.7125
 For  7  Negn Accurcy Score 0.69375
 For  8  Negn Accurcy Score 0.7125
 For  9  Negn Accurcy Score 0.7
 For  10  Negn Accurcy Score 0.7
 For  11  Negn Accurcy Score 0.675
 For  12  Negn Accurcy Score 0.66875
 For  13  Negn Accurcy Score 0.68125
 For  14  Negn Accurcy Score 0.6625
 For  15  Negn Accurcy Score 0.6625
 For  16  Negn Accurcy Score 0.65
 For  17  Negn Accurcy Score 0.6625
 For  18  Negn Accurcy Score 0.66875
 For  19  Negn Accurcy Score 0.65
 For  20  Negn Accurcy Score 0.65625
 For  21  Negn Accurcy Score 0.675
 For  22  Negn Accurcy Score 0.65625
 For  23  Negn Accurcy Score 0.6625
 For  24  Negn Accurcy Score 0.65625
 For  25  Negn Accurcy Score 0.64375
 For  26  Negn Accurcy Score 0.64375
 For  27  Negn Accurcy Score 0.6375
 For  28  Negn Accurcy Score 0.625
 For  29  Negn Accurcy Score 0.61875
 For  30  Negn Accurcy Score 0.6125
 For  31  Negn Accurcy Score 0.63125
 For  32  Negn Accurcy Score 0.61875
 For  33  Negn Accurcy Score 0.63125
 For  34  Negn Accurcy Score 0.61875
 For  35  Negn Accurcy Score 0.60625
 For  36  Negn Accurcy Score 0.6125
 For  37  Negn Accurcy Score 0.60625
 For  38  Negn Accurcy Score 0.5875
 For  39  Negn Accurcy Score 0.5875
 For  40  Negn Accurcy Score 0.6

In [22]:
for i in range (1,41):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    y_test_pred = model.predict(x_test)
    print(" For ",i," Negn Accurcy Score"  , accuracy_score(y_test,y_test_pred))

 For  1  Negn Accurcy Score 0.7037037037037037
 For  2  Negn Accurcy Score 0.6666666666666666
 For  3  Negn Accurcy Score 0.6851851851851852
 For  4  Negn Accurcy Score 0.7037037037037037
 For  5  Negn Accurcy Score 0.7037037037037037
 For  6  Negn Accurcy Score 0.7037037037037037
 For  7  Negn Accurcy Score 0.6666666666666666
 For  8  Negn Accurcy Score 0.6481481481481481
 For  9  Negn Accurcy Score 0.6481481481481481
 For  10  Negn Accurcy Score 0.6666666666666666
 For  11  Negn Accurcy Score 0.6666666666666666
 For  12  Negn Accurcy Score 0.6296296296296297
 For  13  Negn Accurcy Score 0.6481481481481481
 For  14  Negn Accurcy Score 0.6481481481481481
 For  15  Negn Accurcy Score 0.6296296296296297
 For  16  Negn Accurcy Score 0.6481481481481481
 For  17  Negn Accurcy Score 0.6296296296296297
 For  18  Negn Accurcy Score 0.6481481481481481
 For  19  Negn Accurcy Score 0.6111111111111112
 For  20  Negn Accurcy Score 0.6111111111111112
 For  21  Negn Accurcy Score 0.6111111111111112
 For  22  Negn Accurcy Score 0.6296296296296297
 For  23  Negn Accurcy Score 0.6111111111111112
 For  24  Negn Accurcy Score 0.5925925925925926
 For  25  Negn Accurcy Score 0.5925925925925926
 For  26  Negn Accurcy Score 0.5740740740740741
 For  27  Negn Accurcy Score 0.5925925925925926
 For  28  Negn Accurcy Score 0.5925925925925926
 For  29  Negn Accurcy Score 0.6111111111111112
 For  30  Negn Accurcy Score 0.6111111111111112
 For  31  Negn Accurcy Score 0.6111111111111112
 For  32  Negn Accurcy Score 0.6111111111111112
 For  33  Negn Accurcy Score 0.6111111111111112
 For  34  Negn Accurcy Score 0.6111111111111112
 For  35  Negn Accurcy Score 0.6111111111111112
 For  36  Negn Accurcy Score 0.6111111111111112
 For  37  Negn Accurcy Score 0.6296296296296297
 For  38  Negn Accurcy Score 0.5925925925925926
 For  39  Negn Accurcy Score 0.6111111111111112
 For  40  Negn Accurcy Score 0.6111111111111112

## For Normalized Data

In [29]:
x = minmax.fit_transform(x)

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=12,stratify=y)
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train,y_train)
y_train_pred = model.predict(x_train)
print("Accurcy Score"  , accuracy_score(y_train,y_train_pred))

Accurcy Score 0.7375

In [32]:
for i in range (1,41,2):
    model = KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    y_train_pred = model.predict(x_train)
    print(" For ",i," Negn Accurcy Score"  , accuracy_score(y_train,y_train_pred))

 For  1  Negn Accurcy Score 1.0
 For  3  Negn Accurcy Score 0.775
 For  5  Negn Accurcy Score 0.7375
 For  7  Negn Accurcy Score 0.7
 For  9  Negn Accurcy Score 0.7125
 For  11  Negn Accurcy Score 0.675
 For  13  Negn Accurcy Score 0.66875
 For  15  Negn Accurcy Score 0.65625
 For  17  Negn Accurcy Score 0.65
 For  19  Negn Accurcy Score 0.64375
 For  21  Negn Accurcy Score 0.65
 For  23  Negn Accurcy Score 0.63125
 For  25  Negn Accurcy Score 0.64375
 For  27  Negn Accurcy Score 0.61875
 For  29  Negn Accurcy Score 0.625
 For  31  Negn Accurcy Score 0.6125
 For  33  Negn Accurcy Score 0.6125
 For  35  Negn Accurcy Score 0.61875
 For  37  Negn Accurcy Score 0.6
 For  39  Negn Accurcy Score 0.6

### Conclusion : KNN normal Model With 4 Neighbour is our Hero